/**
 * ================================================================
 * READSY - WEB APPLICATION
 * Main App Component & Routing Configuration
 * ================================================================
 * File: src/App.tsx
 * Purpose: Application initialization, authentication setup, routing
 *
 * Key Sections:
 * 1. SuperTokens Configuration (line ~22-41)
 *    - Authentication setup (email, Google, sessions)
 *    - Backend API: http://localhost:3000
 *
 * 2. Route Setup (line ~43-105)
 *    - All routes protected with SessionAuth
 *    - SuperTokens auth routes auto-generated
 *
 * Available Routes:
 * ┌────────────────────────────────────────────┐
 * │ /          → Dashboard (main page)         │
 * │ /home      → Home page                     │
 * │ /discover  → Book discovery page           │
 * │ /books     → Books (alias for discover)    │
 * │ /search    → Search page                   │
 * │ /auth/*    → Auth pages (SuperTokens)      │
 * └────────────────────────────────────────────┘
 *
 * Component Files:
 * → src/components/Dashboard.tsx - Main dashboard
 * → src/components/Home.tsx - Home page
 * → src/components/Discover.tsx - Book discovery
 * → src/components/Search.tsx - Search functionality
 * → src/components/AuthLayout.tsx - Auth wrapper
 *
 * To Add New Route:
 * 1. Create component in src/components/
 * 2. Import at the top of this file
 * 3. Add <Route> with SessionAuth wrapper
 * 4. Reference COMPONENT_GUIDE.md for patterns
 *
 * See: WEB_DOCUMENTATION.md → Routing section
 * ================================================================
 */

import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import { getSuperTokensRoutesForReactRouterDom } from "supertokens-auth-react/ui";
import SuperTokens, { SuperTokensWrapper } from "supertokens-auth-react";
import EmailPassword from "supertokens-auth-react/recipe/emailpassword";
import ThirdParty from "supertokens-auth-react/recipe/thirdparty";
import Session from "supertokens-auth-react/recipe/session";
import { SessionAuth } from "supertokens-auth-react/recipe/session";
import * as reactRouterDom from "react-router-dom";
import { EmailPasswordPreBuiltUI } from "supertokens-auth-react/recipe/emailpassword/prebuiltui";
import { ThirdPartyPreBuiltUI } from "supertokens-auth-react/recipe/thirdparty/prebuiltui";
import { Home } from "./components/Home";
import { Discover } from "./components/Discover";
import { Search } from "./components/Search";
import { ThemeProvider } from "./context/darkmodeContext";
import { BooksPage } from "./components/BooksPage";
import { BookDetails } from "./components/BookDetails";
import { AuthorDetails } from "./components/AuthorDetails";
import { UserProfile } from "./components/UserProfile";
import { AuthorsPage } from "./components/AuthorsPage";
import { Genre } from "./components/Genres";
import { AddBook } from "./components/AddBook";
import "./components/css/auth.css";

SuperTokens.init({
	appInfo: {
		appName: "Readsy",
		apiDomain: "http://localhost:3002", // Backend API domain
		websiteDomain: "http://localhost:5173", // Frontend website domain
		apiBasePath: "/auth",
		websiteBasePath: "/auth",
	},
	clientType: "web",
	recipeList: [
		EmailPassword.init({}),
		ThirdParty.init({
			signInAndUpFeature: {
				providers: [ThirdParty.Google.init()],
			},
		}),
		Session.init({
			sessionTokenFrontendDomain: "localhost",
		}),
	],
});

export default function App() {
	return (
		<SuperTokensWrapper>
			<BrowserRouter>
				<ThemeProvider>
					<Routes>
						{/* SUPERTOKENS AUTH ROUTES - Auto-generated by SuperTokens */}
						{getSuperTokensRoutesForReactRouterDom(reactRouterDom, [
							ThirdPartyPreBuiltUI,
							EmailPasswordPreBuiltUI,
						])}

						{/* ===== APPLICATION ROUTES ===== */}
						{/* All routes require active session (protected by SessionAuth) */}

						{/* DASHBOARD - Main entry point & home */}
						{/* File: src/components/Dashboard.tsx */}

						{/* HOME PAGE - User's personal dashboard */}
						{/* File: src/components/Home.tsx */}
						<Route
							path="/"
							element={
								<SessionAuth>
									<Home />
								</SessionAuth>
							}
						/>

						{/* DISCOVER - Browse and discover books */}
						{/* File: src/components/Discover.tsx */}
						<Route
							path="/discover"
							element={
								<SessionAuth>
									<Discover />
								</SessionAuth>
							}
						/>

						{/* BOOKS - Alias route for /discover */}
						{/* File: src/components/Discover.tsx */}
						<Route
							path="/books"
							element={
								<SessionAuth>
									<Search />
								</SessionAuth>
							}
						/>

						{/* SEARCH - Search for books */}
						{/* File: src/components/Search.tsx */}
						<Route
							path="/search"
							element={
								<SessionAuth>
									<Search />
								</SessionAuth>
							}
						/>


						{/* ===== ROUTE REDIRECTS ===== */}
						{/* Old route names redirect to new ones */}
						<Route path="/dashboard" element={<Navigate to="/" replace />} />


						{/* BOOKS' PAGE - To see all the books */}
						{/* File: src/components/BooksPage.tsx */}
						<Route
							path="/bookspage"
							element={
								<SessionAuth>
									<BooksPage />
								</SessionAuth>
							}
						/>

						{/* BOOKS' DETAILS - To see all information about a book */}
						{/* File: src/components/BooksDetails.tsx */}
						<Route
							path="/book/:id"
							element={
								<SessionAuth>
									<BookDetails />
								</SessionAuth>
							}
						/>

						{/* AUTHORS' DETAILS - To see all information about the an author */}
						{/* File: src/components/AuthorDetails.tsx */}
						<Route
							path="/author/:id"
							element={
								<SessionAuth>
									<AuthorDetails />
								</SessionAuth>
							}
						/>

						{/* AUTHORS' PAGE - To see all authors */}
						{/* File: src/components/AuthorsPage.tsx */}
						<Route
							path="/authorspage"
							element={
								<SessionAuth>
									<AuthorsPage />
								</SessionAuth>
							}
						/>

						{/* USER PROFILE - To see all information about the current user */}
						{/* File: src/components/UserProfile.tsx */}
						<Route
							path="/user/:userId"
							element={
								<SessionAuth>
									<UserProfile />
								</SessionAuth>
							}
						/>

						{/* ADD BOOK - To add a new book to the system */}
						{/* File: src/components/AddBook.tsx */}
						<Route
							path="/add-book"
							element={
								<SessionAuth>
									<AddBook />
								</SessionAuth>
							}
						/>

						{/* GENRES - To see all books having the selected genre */}
						{/* File: src/components/Genre.tsx */}
						<Route
							path="/genres/:id"
							element={
								<SessionAuth>
									<Genre />
								</SessionAuth>
							}
						/>
						{/*FOR ALL GENRES */}
						<Route
							path="/genres"
							element={
								<SessionAuth>
									<Genre />
								</SessionAuth>
							}
						/>

						{/* ===== ROUTE REDIRECTS ===== */}
						{/* Old route names redirect to new ones */}
						<Route
							path="/dashboard"
							element={
								<Navigate to="/" replace />
							} />
					</Routes>


				</ThemeProvider>
			</BrowserRouter>
		</SuperTokensWrapper>
	);
}
